# Uncomment the next line to define a global platform for your project
 platform :ios, '15.0'

target 'JXPlayer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SJVideoPlayer', '3.4.3'
  pod 'SJMediaCacheServer', '2.1.6'
  

end
