# Uncomment the next line to define a global platform for your project
 platform :ios, '15.0'

target 'JXPlayer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'SJBaseVideoPlayer', :git => 'https://github.com/zengjuexin/SJBaseVideoPlayer.git', :tag => '3.7.7.2'
  pod 'SJVideoPlayer'
  pod 'SJMediaCacheServer', '2.1.6'
  

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings.delete('EXCLUDED_ARCHS[sdk=iphonesimulator*]')
      config.build_settings.delete('EXCLUDED_ARCHITECTURES')
    end
  end
end
